cluster: cluster
node:
- hostname: jim1
  port: 22
  private_ip:
    device: ens192
    gateway: 10.203.2.1
    ip: 10.203.2.186
  public_ip: 10.203.1.76
  root_password: password
- hostname: jim2
  port: 22
  private_ip:
    device: ens192
    gateway: 10.203.2.1
    ip: 10.203.2.185
  public_ip: 10.203.1.185
  root_password: password
